.PHONY: run install setup-env setup-bigquery cleanup

run:
	adk web

install:
	pip install -r requirements.txt

setup-env:
	./setup_env.sh

setup-bigquery:
	./setup_bigquery.sh

cleanup:
	./cleanup.sh
